### ISSUE TITLE
centralization

### ISSUE THREAD

**Issue by psztorc** [abrkn/craig-wright-bitcoin-facts#19]
2:36 -- centralization metric is "ratio of edges to nodes" -- says that BCH is not centralized. But later argues that selfish mining is not a problem because the network is centralized. ???
https://www.youtube.com/watch?v=RpWt2RKTTjQ

**Comment by psztorc** [comment]
low priority, as this one is just confusing more than anything

**Comment by abrkn** [comment]
Too complex to add
